[project]
name = "sensor-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "polars>=1.31.0",
]

[tool.pyright]
typeCheckingMode = "strict"