[project]
name = "sensor-data-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "polars>=1.31.0",
    "ray>=2.48.0",
]

[tool.pyright]
typeCheckingMode = "strict"
