# Ray Cluster config for Kubernetes
apiVersion: v1
kind: Namespace
metadata:
  name: ray-cluster
---
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: sensor-ray-cluster
  namespace: ray-cluster
spec:
  rayVersion: '2.10.0'
  headGroupSpec:
    serviceType: ClusterIP
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        containers:
        - name: ray-head
          image: python:3.13-slim
          command: ["ray", "start", "--head", "--port=6379", "--dashboard-host=0.0.0.0"]
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
  workerGroupSpecs:
  - groupName: worker-group
    replicas: 2
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: python:3.13-slim
          command: ["ray", "start", "--address=ray-head:6379"]
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 1
              memory: 2Gi
